import { mutation } from "./_generated/server";

const dancesData = [
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "Abba Cadabra",
    song_artist: "ABBA",
    song_name: "ABBA medley",
    video_url: "https://youtu.be/EUTdjYj9oE0",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "Achy Breaky Heart",
    song_artist: "Billy Ray Cyrus",
    song_name: "Achy Breaky Heart",
    video_url: "https://youtu.be/yoiBwrQw8tk",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "No One Needs To Know",
    song_artist: "Shania Twain",
    song_name: "No One Needs To Know",
    video_url: "https://youtu.be/FBYhEylfP_M",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "El De Los Ojos Negros",
    song_artist: "Sparx",
    song_name: "El De Los Ojos Negros",
    video_url: "https://youtu.be/0OhjmxazgFg",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "Mamma Maria",
    song_artist: "Ricchi E Poveri",
    song_name: "Mamma Maria",
    video_url: "https://youtu.be/scSj8Ni8kYc",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "Oh Oh Oh",
    song_artist: "Stephen McQueen",
    song_name: "Oh Oh Oh",
    video_url: "https://youtu.be/kO9f1-v9JVY",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2024,
    dance_name: "Take Me Home",
    song_artist: "John Denver",
    song_name: "Take Me Home, Country Roads",
    video_url: "https://youtu.be/UuB_KxgIl7w",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Always Will",
    song_artist: "Ace of Base",
    song_name: "Always Have, Always Will",
    video_url: "https://youtu.be/JKNs0ga0HKo",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Runaround Sue",
    song_artist: "Dion",
    song_name: "Runaround Sue",
    video_url: "https://youtu.be/bjSRNTQT95k",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Darlin'",
    song_artist: "Johnny Reid",
    song_name: "Darlin'",
    video_url: "https://youtu.be/awYoRH6NReM",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Ride With Me",
    song_artist: "The Mavericks",
    song_name: "Ride With Me",
    video_url: "https://youtu.be/kxkET_uTo7o",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "All In My Head",
    song_artist: "Alvaro Estrella",
    song_name: "All In My Head",
    video_url: "https://youtu.be/Xa0lRvuBzsQ",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Honky Tonk Highway",
    song_artist: "Luke Combs",
    song_name: "Honky Tonk Highway",
    video_url: "https://youtu.be/C0AgG06F0XI",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Mambo (bye bye)",
    song_artist: "Perry Como",
    song_name: "Papa Loves Mambo",
    video_url: "https://youtu.be/LHTA-rtNtPA",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Let Your Love Flow",
    song_artist: undefined, // NULL in original data
    song_name: "Let Your Love Flow",
    video_url: "https://youtu.be/yULMjZEDKiY",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "I Got A Woman",
    song_artist: "Rudedog; Ray Charles",
    song_name: "I Gotta Woman",
    video_url: "https://youtu.be/WF6Chu5YuXo",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Bambola",
    song_artist: "DJ Guido Arcangeli",
    song_name: "Bambola Italiana",
    video_url: "https://youtu.be/XmPvcRceAm8",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2024,
    dance_name: "Darling",
    song_artist: "Heather Myles",
    song_name: "Who Did You Call Darlin'",
    video_url: "https://youtu.be/awYoRH6NReM",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "On the road again",
    song_artist: "Willie Nelson",
    song_name: "On the road again",
    video_url: "https://youtu.be/mK9YlEgoly4",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "Banjo Boogie",
    song_artist: "HardNox",
    song_name: "Banjo Boogie",
    video_url: "https://youtu.be/CE7Z_-pzsks",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "She Bangs",
    song_artist: "Ricky Martin",
    song_name: "She Bangs",
    video_url: "https://youtu.be/YcBWj1VnjFQ",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "Coward of the country",
    song_artist: "Kenny Rogers",
    song_name: "Coward of the Country",
    video_url: "https://youtu.be/vurIiAra4Io",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "Boom Boom Boom Boom",
    song_artist: "Vengaboys",
    song_name: "Boom Boom Boom Boom",
    video_url: "https://youtu.be/uluRivOGNK0",
  },
  {
    lesson_period: "Voorjaar",
    lesson_year: 2025,
    dance_name: "Good to go",
    song_artist: "Lonis",
    song_name: "Good to go",
    video_url: "https://youtu.be/1JIf-Pfr_4o",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Beautiful Day",
    song_artist: "Dave Sheriff",
    song_name: "Beautiful Day",
    video_url: "https://youtu.be/UoLfaTe0eqQ",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Knock Knock",
    song_artist: "Jake Savoretti",
    song_name: "Knock Knock",
    video_url: "https://youtu.be/szg4Iu76tFQ",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Dans Met Ons Mee",
    song_artist: "Marita's Liedje",
    song_name: "Dans Met Ons Mee",
    video_url: "https://youtu.be/mctTX3vjjI8",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Cowboy Up",
    song_artist: "Jil Johnson",
    song_name: "Cowboy Up",
    video_url: "https://youtu.be/z0VDkE93M4A",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Only Dreamers",
    song_artist: "Helene Fisher",
    song_name: "Only Dreamers",
    video_url: "https://youtu.be/mYgRdNb7Bek",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "The Door",
    song_artist: "Teddy Swims",
    song_name: "The Door",
    video_url: "https://youtu.be/2RDj1BNrEq8",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "The Belle of Liverpool",
    song_artist: "Derek Ryan",
    song_name: "The Belle of Liverpool",
    video_url: "https://youtu.be/f5ADJ2-w6Lo",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "La Camisa Negra",
    song_artist: "Juanes",
    song_name: "La Camisa Negra",
    video_url: "https://youtu.be/fuS1d4pe_zQ",
  },
  {
    lesson_period: "Najaar",
    lesson_year: 2025,
    dance_name: "Back to the Start",
    song_artist: "Michael Schulte",
    song_name: "Back to the Start",
    video_url: "https://youtu.be/D-bDFg5JMos",
  },
];

export const populateLijndances = mutation(async (ctx) => {
  const now = Date.now();

  for (const dance of dancesData) {
    await ctx.db.insert("linedance_dances", {
      lesson_period: dance.lesson_period,
      lesson_year: dance.lesson_year,
      dance_name: dance.dance_name,
      song_artist: dance.song_artist,
      song_name: dance.song_name,
      video_url: dance.video_url,
      createdAt: now,
      updatedAt: now,
    });
  }

  return { success: true, inserted: dancesData.length };
});
